### ISSUE TITLE
Request Example + Bonus Question

### ISSUE THREAD

**Issue by imukai** [mattfrear/Swashbuckle.Examples#31]
This might be a swagger limitation with how it stores schema but I'm going to ask anyway.

I have a common model:  call it Annoying.

I have GET operations that return Annoying or List\<Annoying>.
I have a POST and a PUT operation that take Annoying as a parameter.

There is an ID property inside Annoying that is not needed for the POST or PUT.  I don't want ID showing on the swagger page for example Request to POST or PUT, but I do want it showing in the Response example of the GET.

If I define an example as a dynamic object containing only the properties I want displayed, and decorate it into a SwaggerRequestExample on the POST/PUT methods (typeof(Annoying),typeof(AnnoyingPostExample), I find on the swagger page that this changes ALL examples of Annoying, even on the GET.  I tried typeof(dynamic) but that didn't fly for a SwaggerRequestExample.

If I make a second example of another Annoying and decorate the GET with a SwaggerResponseExample, then it seems to render as expected.

My main question is -- do I have to do this workaround or is there some caveat of a RequestExample that won't override all examples of that data type?

And my bonus question.. did you ever figure out a way to fix the example model from being wrapped inside "application/json" ?  I know you deferred it as being a Swashbuckle or Swagger UI problem, but until they get their act together I need to strip this out, and was trying to find an easy way to do that.

Thanks much, glad to see you're still doing things with this library.

PS - Another workaround would be to use different models for POST/PUT but... not an option in this particular case.

PSS - The application/json thing I cobbled together a javascript solution to inject into swashbuckle's config using the .InjectJavaScript option, but I don't know if I like it.

```js
$(".snippet_json pre code").each(function (idx, element) {
    var ele = $(element);
    var js = JSON.parse(ele.text());
    if (js["application/json"]) {
        //bring everything up a level
        $.each(js["application/json"],
            function(key, val) {
                js[key] = val;
            });
        //delete the offending part.
        delete js["application/json"];
        ele.html(JSON.stringify(js, null, '\t')
            .replace(/\n/g, '<br />')
            .replace(/\t/g,"&nbsp;&nbsp;&nbsp;")
            );
    }
});
```

**Comment by mattfrear** [comment]
> My main question is -- do I have to do this workaround or is there some caveat of a RequestExample that won't override all examples of that data type?

OK so the way Swagger works is the Request objects are only defined once at the end of the document, and each object can only have one example defined.
Response objects on the other hand are defined alongside each operation, and can have an example defined there too. So yes, defining it again on each Response is the right thing to do if you want to have a different example defined for your responses compared to your requests.

Me personally I always define unique objects for requests and responses, which has the downside of having to write a lot of mapping code (or use Automapper).

Yeah I actually removed the `application/json` thing in one version of this library, because most people don't like it, only for others to ask me to bring it back because it should be there according to the Swagger spec. Your javascript hack is a great idea, that way the swagger.json follows the spec and what's displayed in the UX looks correct.

**Comment by mattfrear** [comment]
OK so the `application\json` bonus question seems to be fixed in Swashbuckle.AspNetCore version 3.0, and using my Swashbuckle.AspNetCore.Filters 3.0.
