### ISSUE TITLE
Duplicated JSON Serializer Settings Missing Values

### ISSUE THREAD

**Issue by Sacrilege** [mattfrear/Swashbuckle.Examples#38]
In the file ExamplesOperationFilter there is a new serializer settings instance created by copying values from the controller configuration but some values are missing. In particular I noticed this because I was globally setting a value on DateFormatString but my examples weren't using it when they were rendered. :-)

**Comment by mattfrear** [comment]
I reference "Newtonsoft.Json" version="4.5.6", and in that version DateFormatString does not exist, which is why the setting is not copied.

**Comment by mattfrear** [comment]
I have always been in favour of referencing the _lowest_ version of any dependencies, for maximum compatibility with the largest number of users.

However, since development of Swashbuckle seems to have stopped at 5.6.0, I might as well upgrade to that version, which will also upgrade to Newtonsoft.Json 7.0.1 and fix your issue.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.Examples/3.10.0
