### ISSUE TITLE
Make Request Example for JObject Paramater of POST Call

### ISSUE THREAD

**Issue by mohamedryan** [mattfrear/Swashbuckle.Examples#45]
I have POST Call that accept JObject parameter, and i want to make example for this object
instead of using Model.

this what i have: 

![image](https://user-images.githubusercontent.com/8198561/61629684-a6802a80-ac96-11e9-8193-9a19dfbbaff2.png)

and this the version of swagger i have:

![image](https://user-images.githubusercontent.com/8198561/61629824-1393c000-ac97-11e9-856f-3890d455abe0.png)

**Note:** _in my case here i don't want to use Modal or changing Swagger version_

i tried to do as the pic shown and searched a lot for this.

**Any help??**
and thanks

**Comment by mattfrear** [comment]
Hi Mohamed

Your code looks correct. What do you see on your swagger page?

I must admit I haven't used this project for a couple of years, I only use the AspNetCore version now. Are you using ASP.NET or ASP.NET Core?

I see a user had a similar problem to you in that project too, but I don't think this will help you much.
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/42

**Comment by mohamedryan** [comment]
Hi @mattfrear ,
Thanks for replay

i'm using ASP.Net Web API 2 not Core
also i'm using "Swashbuckle" and "Swashbuckle.Examples" not using "Swashbuckle.AspNetCore"

i saw some comments in some other issues that this case was handled in "Swashbuckle.AspNetCore"

but i need any solutions or any workaround to apply this in my project using "Swashbuckle".

it is possible ?

**Comment by mattfrear** [comment]
> What do you see on your swagger page?

Please post a screenshot

**Comment by mohamedryan** [comment]
This is what is shown:

![image](https://user-images.githubusercontent.com/8198561/61790189-a2374700-ae27-11e9-84bf-acdba3148997.png)

**Comment by mattfrear** [comment]
Hmm, I don't know. It works with Swashbuckle.AspNetCore:
https://medium.com/@joni2nja/generating-swagger-example-dynamic-request-payload-with-swashbuckle-77c09127392c

I just had a quick play:
```csharp
        [HttpPost]
        [Route("api/values/jobjecttest")]
        [SwaggerRequestExample(typeof(JObject), typeof(JObjectExample))]
        public IHttpActionResult PostJObject([FromBody]JObject body)
        {
            return Ok();
        }
```
and 
```csharp
    public class JObjectExample : IExamplesProvider
    {
        public object GetExamples()
        {
            return new JObject
            {
                { "hello", "world" }
            };
        }
    }
```
and I see the same thing as you - nothing. But if you look in the swagger.json which is generated, the example is there:
![image](https://user-images.githubusercontent.com/169179/61840040-04558200-aee4-11e9-919b-40748e5657ac.png)

However what is missing from the swagger.json is a definition for your response in the `definitions` at the bottom. I think that is where the request example that is displayed in swagger-ui comes from.

This is all quite similar to this issue https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/39

Unfortunately, I don't think it can be fixed, but there is a workaround. Instead of taking a `JObject` as a parameter in your controller, you can take a `Dictionary<string, object>`. 
```csharp
public IHttpActionResult PostDictionary([FromBody]Dictionary<string, object> dynamicDictionary)
```
Does that work for you?

**Comment by mohamedryan** [comment]
@mattfrear  Perfect, This workaround worked with me.
Thanks a lot :) 

This what i did:

![image](https://user-images.githubusercontent.com/8198561/61858382-06fdaa80-aed7-11e9-9a9d-57ade80bed6e.png)

![image](https://user-images.githubusercontent.com/8198561/61858466-2b598700-aed7-11e9-962e-122bafc8869e.png)

![image](https://user-images.githubusercontent.com/8198561/61858491-37454900-aed7-11e9-9968-246d4e6f4c3b.png)
