### ISSUE TITLE
Exemple problem with other statut code

### ISSUE THREAD

**Issue by fhenriot-orisha** [mattfrear/Swashbuckle.Examples#67]
Hello,

I use asp.net project in VB with Framework .Net 4.7.2.
I have nugget package.
![image](https://github.com/mattfrear/Swashbuckle.Examples/assets/69668777/949a260a-9173-4299-8eaa-b5fdde431451)

I use SwaggerResponseExample for statut 200 and it's fine.
I want to use SwaggerResponseExample  for other statut code and i always see the default example.

![image](https://github.com/mattfrear/Swashbuckle.Examples/assets/69668777/3d507e99-8668-4404-831d-16ef6cdd9c46)

I want to setup a custom response example for statut 401 but it's not work

![image](https://github.com/mattfrear/Swashbuckle.Examples/assets/69668777/86d3c047-bebb-4cdf-871c-1ad378186b67)

The json format seems good (.../swagger/v1) :

![image](https://github.com/mattfrear/Swashbuckle.Examples/assets/69668777/1f453b07-fbd7-4c38-8962-7080b9662be4)

Is it a UI Bug ?

Thank you

**Comment by fhenriot-orisha** [comment]
If i want to use only one statut like 401. I don't really understand what happend.

![image](https://github.com/mattfrear/Swashbuckle.Examples/assets/69668777/a8cae3b3-52a9-4b06-b2bc-2e6ee15ecca9)

![image](https://github.com/mattfrear/Swashbuckle.Examples/assets/69668777/6f4cdc87-1022-4e13-ae98-91b006a3183f)

![image](https://github.com/mattfrear/Swashbuckle.Examples/assets/69668777/c5d5f978-8b39-49ff-b953-e41136cc4897)

**Comment by mattfrear** [comment]
> I use SwaggerResponseExample for statut 200 and it's fine. I want to use SwaggerResponseExample for other statut code and i always see the default example. 
> Is it a UI Bug ?

Hello! Yes, you've picked it, it's a UI bug. I mention this in the [Known Issues](https://github.com/mattfrear/Swashbuckle.Examples#known-issues).

Swashbuckle (.NET Framework version) hasn't been updated in many years, so it is still using an old version of the UI which has this bug.

I just did a bit of searching, and you will probably be better off to use Swagger-Net instead of Swashbuckle, and [Swagger-Net.Examples](https://github.com/korser1/Swagger-Net.Examples) instead of my Swashbuckle.Examples.

**Comment by fhenriot-orisha** [comment]
Thank you so much.
You save my day !
It's fine with Swagger-Net.
